### ISSUE TITLE
b.color("colorName") error when using resulting color in b.fill() twice.

### ISSUE THREAD

**Issue by trych** [basiljs/basil.js#73]
When `b.fill(myColor)` is used for the _second_ time with a color retrieved by `var myColor = b.color("colorName")`, InDesign throws an error `Color.===() kann mit Instanzen dieser Klasse nicht arbeiten` (sorry, I can't switch my installation to English unfortunately; something along the lines "Color.===() can't work with instances of this class").

I was digging around a bit, the error actually happens in the `checkNull` check that is performed at the beginning of `pub.fill()`. I suspect this is related to the fact, that `b.color("colorName)` returns a swatch instead of a color (as all other `b.color()` variants do, the error does not appear there). Possible fix might be to always return an actual `color` object from `b.color()`.

Here is a script to test (red rect is not really necessary, but makes it look more like a real world script):

```JavaScript
#includepath "~/Documents/;%USERPROFILE%Documents";
#include "basiljs/bundle/basil.js";

function draw() {
  var black = b.color("Black");
  var red = b.color(255, 0, 0);

  b.fill(black);
  b.rect(0, 0, 100, 100);

  b.fill(red);
  b.rect(100, 100, 100, 100)

  b.fill(black); // interrupts with error for me
  b.rect(200, 200, 100, 100);
}

b.go();
```

InDesign CS6, OS X 10.8.5.

Please flag as bug.

**Comment by trych** [comment]
Oh, and this breaks `/scripts/examples/transform/pushMatrix and popMatrix.jsx` (that's how I found the bug in the first place).

**Comment by GitBruno** [comment]
Your real world script works now with: https://github.com/basiljs/basil.js/pull/81

I guess we now need to implement a b.gradient, but that is a different issue :)

**Comment by trych** [comment]
Hi GitBruno, the real world script was already fixed in #75. :)

**Comment by GitBruno** [comment]
Interesting, you need to merge and close this issue then? When I download the latest master, the problem is still there?

**Comment by GitBruno** [comment]
I had a quick look through #75, and it does not seam to address the swatches issue: Not every swatch is an instance Color.

**Comment by trych** [comment]
> Interesting, you need to merge and close this issue then? When I download the latest master, the problem is still there?
Well, yes, it's a pull request that is still pending, since nobody of the basil.js org has reviewed it yet. I cannot merge and close the issue myself. ;)

> I see! You forgot to replace one on line 163 then?
What do you mean? I replaced line old 163
```JavaScript
newCol = findInCollectionByName(currentDoc().swatches, a);
```
by new line 163
``` JavaScript
newCol = findInCollectionByName(currentDoc().colors, a);
```
which fixes the problem in #73 and makes b.color() work with colors, as its name suggests. ;)

See [this commit](https://github.com/basiljs/basil.js/pull/75/commits/e85c17616fc6d7cb7e594c5fb3b0ba9eb934b301).

**Comment by GitBruno** [comment]
Ah right, Sorry, I am kind-of new to git and was going of the master. Good job!

**Comment by trych** [comment]
Hey, no problem! :) I am new myself, so I am also still learning.
If you work on an issue, you should always make sure that it has not been addressed yet – either that it is in master already or that it is addressed in a pull request waiting for review. As you can see above, this issue was referenced in a pull request, and there you could find the info that the bug was fixed with the pull request.

Now we just have to wait for somebody to review. ;)

**Comment by fabiantheblind** [comment]
Sorry for the pending reviews. It will happen ASAP
